AllCops:
  TargetRubyVersion: 2.3

Style/FileName:
  Exclude:
    - "lib/castle-rb.rb"

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"