services:
  - docker

dist: trusty
cache: bundler

git:
  depth: false

test: &test
  stage: Test
  language: ruby
  before_install:
    - yes | gem update --system
  script: bundle exec rake test

jobs:
  include:
    - <<: *test
      rvm: 2.7.0
    - <<: *test
      rvm: 2.6.5
    - <<: *test
      rvm: 2.5.7
    - <<: *test
      rvm: jruby-9.2.9.0

    - stage: coditsu
      language: ruby
      rvm: 2.7.0
      before_install:
        - yes | gem update --system
      script: \curl -sSL https://api.coditsu.io/run/ci | bash

stages:
  - test
  - coditsu
